// Test: TYPE_NESTING_LIMIT
// File: tests/diagnostics/failures/test_nesting_type.wl
// Focus: Rejecting excessively nested type expressions without overflowing the compiler stack.
// Expected Error: "InvalidSyntax: Syntax nesting exceeds the limit of 256."

func main() -> Int {
    let value: Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Vector(Int)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))) = null;
    return 0;
}
